name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'
          bundler-cache: true
          cache-dependency-path: 'docs/Gemfile.lock'

      - name: Setup Pages
        id: pages
        uses: actions/configure-pages@v4

      - name: Build with Jekyll
        working-directory: ./docs
       jekyll build --destination ${{ github.workspace }}/.jekyll-cache/jekyll-site

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: .jekyll-cache/jekyll-site

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4